### ISSUE TITLE
今後の進め方について

### ISSUE THREAD

**Issue by starbuckskenji** [starbuckskenji/skillup-drupal#1]
# 今後の進め方について
## 今後、やっていくこと
Sqllogモジュール開発

## 目的
* Sqllogモジュール開発を通してDrupalのスキルアップを図る
* "完成"が目的ではなく、進めていく中で"発見"や"疑問"を感じること

## 仕様
* SQLログを画面から確認できる
* 全ログ または 権限単位、タグ指定 でログを保持する(まずは全ログでよいです)
* 一覧は以下のカラムを持つ
 * 出力日時
 * SQLログ(前方N文字を表示する)
* SQLログはリンクとする
* SQLログリンクをクリックすると、SQLログ詳細画面へ遷移する
* SQLログ詳細画面で出力されるSQLログは、
 * SQLのプレースホルダにパラメータが入っていること
 * 整形されていること
* 出力日時で降順に出力する

## 特記事項
* Maillogモジュールを参考にすること
* 一覧の絞り込み機能は、とりあえずつくらない(余裕があれば作って下さい)
* 設計書作成は不要(設計書を書く練習にもなるため、進み具合を見て着手しましょう)

## 方針
* 業務もあるため、無理しない程度に進めてください。
* WBSを書く必要はないですが、細かくマイルストーンを設定してください。
* 詳細は、次回の勉強会の際にお伝えしますね。
* まずは学習資材をプルしてもらって、動きを見てもらえるとよいかと思います。

**Comment by starbuckskenji** [comment]
あーそうそう。Sqllogモジュールを作るにあたり、"maillog"を"sqllog"に一括置換してプッシュしておいてください。大文字・小文字に気をつけてください！

**Comment by n-kaneko** [comment]
分からない点は,そのつど質問させていただきたいと思います。
よろしくお願いします！！
