### ISSUE TITLE
まずやって！

### ISSUE THREAD

**Issue by starbuckskenji** [starbuckskenji/skillup-drupal#2]
# 次回、勉強会までにやること
* @n-kaneko 
  * Maillogモジュールの動きを見る
   * - [x] contactモジュールを有効にする
   * - [x] /contact へアクセスしてメールを飛ばす
   * - [x] Maillog一覧画面で確認
  * 開発環境構築
   * - [x] git
   * - [x] クローンする
   * - [x ] Eclipse でデバッグの設定をする
   * - [x] Develモジュールを入れて、有効にする
  * モジュール改修
   * - [x] Maillog を Sqllog に置換して、プッシュをお願いします

**Comment by n-kaneko** [comment]
遅くなってすいません。
gitの設定などの環境構築は来週中に完了させる予定です。

**Comment by starbuckskenji** [comment]
おそらくつまづくと思うので、聞いてもらってよいですよ:)

**Comment by n-kaneko** [comment]
はい！ありがとうございます。

**Comment by n-kaneko** [comment]
開発環境の構築が終了しました。
